name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Build
        env:
          GOGGC: 0
          GOOS: 'linux'
          GOARCH: 'amd64'
        run: |
          go build --ldflags="-extldflags "-static" -X github.com/MultiMx/QPT/global.VERSION='${{ steps.get_version.outputs.VERSION }}' -X github.com/MultiMx/QPT/modules/github.AccessToken='${{ secrets.GITHUB_ACCESS_KEY }}' -s -w" -o qpt_linux_amd64
          export GOARCH=arm64
          go build --ldflags="-extldflags "-static" -X github.com/MultiMx/QPT/global.VERSION='${{ steps.get_version.outputs.VERSION }}' -X github.com/MultiMx/QPT/modules/github.AccessToken='${{ secrets.GITHUB_ACCESS_KEY }}' -s -w" -o qpt_linux_arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qpt_linux_amd64
            qpt_linux_arm64
